name: Run gradle build

on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: qupath/actions/.github/workflows/gradle.yml@main
