name: Publish release to SciJava Maven

on:
  workflow_dispatch:
    inputs:
      release:
        type: boolean
        description: Should this be a release? (if not, do a snapshot)
        required: true

jobs:
  build:
    name: Publish release
    uses: qupath/actions/.github/workflows/scijava-maven.yml@main
    secrets: inherit
    with:
      release: ${{ inputs.release }}
